### ISSUE TITLE
Struggling to add plugin

### ISSUE THREAD

**Issue by mbagatini** [theonlyducks/videojs-zoom#1]
Hello Giovane,

I'm struggling to enable the plugin to the player on my React app. The player doesn't show any option to zoom.

Only installing and importing the libraries should be enough to make it work? 

```
import '@theonlyducks/videojs-zoom';
import '@theonlyducks/videojs-zoom/styles';
```

Thanks!

**Comment by giovanesantossilva** [comment]
Hello, we are checking here and just the styles are important first and then the js and performing the example should work

```js
const video = videojs('my-video');
const zoomPlugin = video.zoomPlugin();
```

Are you using class component or functional component?

**Comment by giovanesantossilva** [comment]
Problem solved, thank you for using our library and we will be available to correct any problem. Thanks!

**Comment by mbagatini** [comment]
Thanks a lot for helping to solve the problem!

For the ones who might face the same problem, I'll share a piece of code as example:

```javascript
import { useEffect } from 'react';

import 'video.js/dist/video-js.min.css'
import videojs from 'video.js'

import '@theonlyducks/videojs-zoom';
import '@theonlyducks/videojs-zoom/styles';

function App() {
	useEffect(() => {
		const video = videojs('my-video')
		video.zoomPlugin()
	}, [])

	return (
		<div className="App">
			<video id="my-video" className="video-js vjs-default-skin" controls preload="auto" width="800" height="400" data-setup='{}'>
				<source src="example.mp4" type="video/mp4" />
			</video>
		</div>
	)
}

export default App
```
