### ISSUE TITLE
Video.js icons out-of-date

### ISSUE THREAD

**Issue by mbagatini** [theonlyducks/videojs-zoom#2]
Hi guys,

I would like to report a issue abou video.js icons. It seems to be out of date according its font repository.

https://github.com/videojs/font

I noticed it using the plugin on a project, instead of showing the setting icon, it was showing the download icon.

![image](https://user-images.githubusercontent.com/17517028/231440533-c15154ac-aa1c-4451-8000-588b270206b0.png)

**Comment by giovanesantossilva** [comment]
Good morning, I checked here and it must be a library overlapping problem, but I will try to change the icon library in the next version, thanks!
