### ISSUE TITLE
Non-node version?

### ISSUE THREAD

**Issue by Rich2020** [theonlyducks/videojs-zoom#7]
I am not using NodeJS. Can I still use this plugin?

**Comment by giovanesantossilva** [comment]
It is not yet possible to use it without the node, but I will provide it in the new versions,

**Comment by giovanesantossilva** [comment]
Hello my friend, the version without Node is now available. Thank you for reporting the issue, and I'll go ahead and close it. If you encounter any new problems, feel free to report them here. Thanks again!
