### ISSUE TITLE
Manual disable plugin

### ISSUE THREAD

**Issue by HODOR-GAMER** [theonlyducks/videojs-zoom#8]
How to manualyy disable this plugin? In docs i dont find anything about this. e.g. i need when user click some button this plugin shoud be disable, and when click othor button plugin enabled
or this plugin initialized only one time and cant be disabled?

**Comment by KlerKpn** [comment]
The documentation does not provide for this yet, but in my project I solved a similar case this way
tailwind example, but you can do same thing with js toggle
```
.vjs-zoom-duck.vjs-zoom-duck-8.vjs-control.vjs-button {
  @apply hidden lg:block;
}
```

**Comment by giovanesantossilva** [comment]
Hello, thank you for reporting the problem, I will check to implement this in the next version, once completed I will close the issue here.

**Comment by giovanesantossilva** [comment]
Hello my friend, the [version](https://github.com/theonlyducks/videojs-zoom/releases/tag/v1.3.4) with the ability to enable and disable the plugin completely is now available. Thank you for reporting the issue, and I'll go ahead and close it. If you encounter any new problems, feel free to report them here. Thanks again!
